# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7eef4e1392ac0b328e3f691da67a1145d37ebba7d66e98b8354288f3f2eb7d615f04d23291d8c84ad4937df850a7ce1447f14f942bbae26c9fcec40c0652f3bf

test:
  secret_key_base: 3b4935b25df9ac0cf2669b356b2c476fddd3400c571bb48869de0748b257c82cce27aa2a72194ebd79ed41a05e74afb5e3aac4b864d88f564cac9c9119e37b1a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
